version: '3.8'

services:
  api-despesas:
    image: minhagrana-api:latest
    networks:
      - network_public
      - internal_db_network
    environment:
      DATABASE_URL: "postgresql://postgres:TxFEUjXbqEfbaawTVmdE@postgresql:5432/minhagrana"
      CORS_ORIGIN: "https://despesas.seulimacasafacil.com.br"
      PORT: "3000"
      NODE_ENV: "production"
      NEXT_PUBLIC_API_BASE_URL: "https://despesas.seulimacasafacil.com.br"
      NEXT_TELEMETRY_DISABLED: "1"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"
        traefik.http.routers.api-despesas.rule: "Host(`despesas.seulimacasafacil.com.br`)"
        traefik.http.routers.api-despesas.entrypoints: "websecure"
        traefik.http.routers.api-despesas.tls.certresolver: "letsencrypt"
        traefik.http.services.api-despesas.loadbalancer.server.port: "3000"

  postgresql:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: minhagrana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: TxFEUjXbqEfbaawTVmdE
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_db_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:
    driver: local

networks:
  network_public:
    external: true
  internal_db_network:
    internal: true
